### ISSUE TITLE
Web Content process keeps running

### ISSUE THREAD

**Issue by jtbandes** [jtbandes/quicklookjs#7]
> Its creating a new process each time I open quicklook. Also seems like its created after the quicklook is closed but that could be just a delay and because I was doing it pretty fast. Its even creating multiple processes for the same file
>
> https://github.com/jtbandes/quicklookjs/assets/7613915/06acba44-79bd-4bbb-b4e6-ad13e1ddf440
>
> Also looks like these are never killed, I found them by going through activity monitor after it handn't been restarted for days and found 50+ of these.

_Originally posted by @repalash in https://github.com/jtbandes/quicklookjs/issues/1#issuecomment-2057315814_

**Comment by repalash** [comment]
Hey, sorry, for the record i meant to say 15+ processes, just realised I wrote 50 by mistake.
